#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint..."
npm run lint

echo "🔒 Running security check..."
npm run snyk:test -- --fail-on=high || echo "⚠️ Vulnerabilities found but commit continues"

echo "✨ Running format..."
npx lint-staged